//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivaldi.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vivaldi.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede iniciar sesión, No hay dispositivo disponibles..
        /// </summary>
        public static string DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, seleccione una huella.
        /// </summary>
        public static string EmptyFinger {
            get {
                return ResourceManager.GetString("EmptyFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, ingrese el numero de documento.
        /// </summary>
        public static string EmptyNumeroDoc {
            get {
                return ResourceManager.GetString("EmptyNumeroDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, ingrese la cotraseña.
        /// </summary>
        public static string EmptyPass {
            get {
                return ResourceManager.GetString("EmptyPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor,  seleccione tipo de documento.
        /// </summary>
        public static string EmptyTipoDoc {
            get {
                return ResourceManager.GetString("EmptyTipoDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, ingrese el token de seguridad.
        /// </summary>
        public static string EmptyToken {
            get {
                return ResourceManager.GetString("EmptyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, ingrese el usuario.
        /// </summary>
        public static string EmptyUser {
            get {
                return ResourceManager.GetString("EmptyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener la llave de cifrado de la huella, por favor comuníquese con su administrador.
        /// </summary>
        public static string ErrorKey {
            get {
                return ResourceManager.GetString("ErrorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar solicitud al servidor.
        /// </summary>
        public static string ErrorServer {
            get {
                return ResourceManager.GetString("ErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al iniciar sesión.
        /// </summary>
        public static string ErrorSession {
            get {
                return ResourceManager.GetString("ErrorSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Token incorrecto.
        /// </summary>
        public static string ErrorToken {
            get {
                return ResourceManager.GetString("ErrorToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a e1tr4b4aj0@*2019.
        /// </summary>
        public static string Iv {
            get {
                return ResourceManager.GetString("Iv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hhssy3737373ggBh.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a se requiere cambio de contraseña, por favor comuníquese con su administrador.
        /// </summary>
        public static string PassChange {
            get {
                return ResourceManager.GetString("PassChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una sesión abierta con este usuario. Desea cerrarla e iniciar sesión en ésta estación?.
        /// </summary>
        public static string SessionExist {
            get {
                return ResourceManager.GetString("SessionExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo para el tratamiento de datos no existe, por favor comuníquese con su administrador..
        /// </summary>
        public static string TreatmentNoExist {
            get {
                return ResourceManager.GetString("TreatmentNoExist", resourceCulture);
            }
        }
    }
}
